### ISSUE TITLE
Failed to activate the linter-ansible-linting package

### ISSUE THREAD

**Issue by bottlelee** [mschuchard/linter-ansible-linting#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [linter-ansible-linting](https://github.com/mschuchard/linter-ansible-linting) package 1.2.2

### Stack Trace

Failed to activate the linter-ansible-linting package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/linter-ansible-linting-1.2.2/lib/main.js:118:5)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
ansible-vault 0.3.1 
atom-jinja2 0.5.0 
git-plus 7.3.0 
linter-ansible-linting 1.2.2 
markdown-format 2.5.1 
```

**Comment by mschuchard** [comment]
I am seeing `atom-package-deps` as still available and functioning from npm. Did you maybe have a network issue while installing?

**Comment by mschuchard** [comment]
ping @bottlelee

**Comment by bottlelee** [comment]
@mschuchard 
Thanks for the reply.
I've solved the problem. It's all about the GFW of China. I can't use 'apm' directly, so I have to download git_plus from github.
Then I must enter into the package directory and run 'npm install', everything works fine until then.
